#!/usr/bin/env bash
set -euo pipefail

export SPRING_DATASOURCE_URL="${SPRING_DATASOURCE_URL:-jdbc:h2:mem:tradingdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL}"
export SPRING_DATASOURCE_USERNAME="${SPRING_DATASOURCE_USERNAME:-sa}"
export SPRING_DATASOURCE_PASSWORD="${SPRING_DATASOURCE_PASSWORD:-}"
export TRADING_RISK_PERCENT="${TRADING_RISK_PERCENT:-0.01}"
export TRADING_RISK_MAX_PERCENT="${TRADING_RISK_MAX_PERCENT:-0.02}"
export TRADING_RISK_MIN_STOP_LOSS_PIPS="${TRADING_RISK_MIN_STOP_LOSS_PIPS:-1}"

./mvnw spring-boot:run
